### ISSUE TITLE
Pally Judgement cooldown possible broken

### ISSUE THREAD

**Issue by NoControl712** [Tojaso/Raven#5]
Hi, I am sorry if this is not the proper place to submit issues to you but I do not have a curseforge account to comment and I was having trouble signing up. Anyway, when trying to create a cooldown bar for Judgement on my Pally, it will not monitor the cooldown or display charges if I am spec'd for two charges. I have tried several things:

- Show When Ready options always shows the bar even when it is not ready and not usable.
- I have setup a cooldown bar on a similar ability, such as hammer of the righteous in the protection spec which has identical charges and recharge time. This bar works fine but not when I do the exact same thing on Judgement.
- I have also tried setting up a custom condition to monitor Judgement and set it up for spell ready condition. Even when Judgement is ready to use, the condition evaluates to false. So this leads me to believe this issue is not exclusive to just the custom bar, but Judgement spell conditions overall.

Again, sorry if this is not where I should post. Just wanted to bring it to your attention and maybe you have knowledge of other Pally players having this issue.

Thanks

**Comment by Tojaso** [comment]
Maybe you entered "Judgement" instead of "Judgment"? Note that Judgment is the spelling in the spell book. Using Judgement instead finds the same icon but doesn't actually work. Also note that a Judgment bar will show up in the standard Cooldowns group. Let me know if that was the issue.

This is a fine place to leave questions since it generates an email to let me know that one is available.

Update: Forgot to say that I am still planning to check this with two charge spec when get a chance...

**Comment by NoControl712** [comment]
Wow, I feel soo silly. Yeah, I was typing Judgement. When typing Judgment it works. Sorry about that. Thanks for the help.
